server:
  port: 8088
spring:
  profiles:
    active: ${ENV}
  application:
    name: client-provider
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: dubbo-felix-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 28800

tracking:
  trace:
    sample: randompercent
  rate: 1
